ARG version
FROM almalinux:${version:-9}
ENV Course="Devops"\
    Trainer="Siva"
ARG duration="120hrs"
ENV duration=duration
RUN echo "Hi, Course is: ${course}, duration is: ${duration}, trainer is: ${trainer}, version: ${version}"
CMD ["sleep","1000"]
