FROM almalinux:version
ARG version="${version}"
ENV Course="Devops"\
    Trainer="Siva"
ARG duration="120hrs"
CMD ["sleep","1000"]

FROM almalinux:9
ENV course="Devops"\
    Trainer="Siva"
ARG Duration="120hrs"
ENV duration=Duration
CMD ["sleep","1000"]